spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/employee_managment_system
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: RBTGOD2@
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDilect

